apiVersion: v1
kind: Service
metadata:
  name: data-demo-api
  labels:
    app: data-demo-api
spec:
  selector:
    app: data-demo-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP